### ISSUE TITLE
NSFW websites.

### ISSUE THREAD

**Issue by lorelolorelo** [firefart/zwiebelproxy#18]
Hey @firefart Is there a simple way to add a kind of blacklist with unwanted sites, to prevent access...

**Comment by firefart** [comment]
Hi,
I could add an config option with blacklisted domains but you would need to add every single website you are not interested in so I think this is not very practical

**Comment by lorelolorelo** [comment]
well worse is not having anything :), I have received some abuse from my VPS provider about some visits that someone found the domain that I had configured... and it has been a bit unpleasant tbh, if you explain to me how to add that config I would be grateful .

**Comment by firefart** [comment]
Hi,
I thought about this and I came up with a solution:
with the latest version you can now define blacklisted words via `-blacklisted-words` or the `ZWIEBEL_BLACKLISTED_WORDS` env variable (separate them by comma). The words are used in a case insensitive boundary regex (`\bword\b`) and if the response body matches the request will be aborted. This way you can define some porn related words instead of blacklisting domains.
Please let me know if that works out for you
